export type Type = { place: string; club: string[] };

export const ClubPlace: Type[] = [
  {
    place: '운동장 앞',
    club: [
      '코아',
      '명월',
      '무릉도원',
      '명지챌린저스',
      '콕콕콕',
      '오버행',
      '명지서법',
      '삼박자',
      '씨네메이션',
      '너나들이',
      '흙',
      'TIME',
      '그림패시만화',
      'COW',
      'UBF',
      'MJTA',
      '실로암',
      'MIRS',
      'IVF',
      'SK루키',
      'PTPI',
    ],
  },
  {
    place: '종합관 앞',
    club: [
      '굴렁쇠',
      '포토랩',
      '디비전',
      'RCY',
      'CCC',
      'CFM',
      '나이너스',
      '비주얼',
      '키비탄',
      'DEPth',
      '바다이야기',
      '나라오르다',
      'BB',
    ],
  },
  {
    place: 'MCC 3층',
    club: ['FC명지', '씨네필', '인액터스', '에뚜알', '파인'],
  },
  {
    place: '종합관 & 학생회관 사이',
    club: ['화이트홀스', '통해', 'MGH', '흑풍', '알', '주리랑'],
  },
];
